"""add user relationship to books

Revision ID: 195e3de75fa9
Revises: 33a37ceab20b
Create Date: 2026-10-07 08:44:02.607863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '195e3de75fa9'
down_revision: Union[str, Sequence[str], None] = '33a37ceab20b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'books',
        sa.Column(
            'user_uid',
            sa.Uuid(),
            nullable=True
        )
    )

    op.create_foreign_key(
        'fk_books_user_uid_users',
        'books',
        'users',
        ['user_uid'],
        ['uid']
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint(
        'fk_books_user_uid_users',
        'books',
        type_='foreignkey'
    )

    op.drop_column(
        'books',
        'user_uid'
    )

   