"""add password hash

Revision ID: a2c90ac0839d
Revises: 7c337de5efc5
Create Date: 2026-10-02 09:47:50.046056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a2c90ac0839d'
down_revision: Union[str, Sequence[str], None] = '7c337de5efc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sqlmodel.sql.sqltypes.UTCDateTime(),
               nullable=False)
    op.alter_column('users', 'update_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sqlmodel.sql.sqltypes.UTCDateTime(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'update_at',
               existing_type=sqlmodel.sql.sqltypes.UTCDateTime(),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sqlmodel.sql.sqltypes.UTCDateTime(),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
